name: Check PR
on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: crate-ci/typos@v1.0.4
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          pattern: gh-approve-deploy
          fail_on_error: true
          github_token: ${{ secrets.github_token }}
